require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - gemfiles/vendor/bundle/**/*
    - vendor/bundle/**/*
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
