require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - gemfiles/vendor/bundle/**/*
    - vendor/bundle/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
